### ISSUE TITLE
Tool alt tabbing when using the refresh button

### ISSUE THREAD

**Issue by Mondarian** [DEFSAK/admin-gui#3]
If you use the refresh button you get alt tabbed back to whatever app you were in before. Not a big issue, just ever so slightly annoying since you have to navigate to the tool again then.

**Comment by Smigg-y** [comment]
this is due to how the gui interfaces with the game, it has to set your game window to the foreground so it can send keystrokes (open console and type the command)

**Comment by Smigg-y** [comment]
> this is due to how the gui interfaces with the game, it has to set your game window to the foreground so it can send keystrokes (open console and type the command)

could most definitely make it so the gui is focused after the fact though.

**Comment by Edmund-Blackadder** [comment]
that would make it more seamless
