### ISSUE TITLE
Hitting Enter doesnt execute the command 

### ISSUE THREAD

**Issue by Mondarian** [DEFSAK/admin-gui#4]
If you want to kick / ban and hit "Enter" after providing the reason (and length in case of ban) then it will play the animation in the bottom right that the command was successfully executed, however in reality it does not do anything. You have to manually press the Ban Hammer button to have the command execute properly. Again, not a huge issue, just confusing at times when you didnt pay attention. Enter should either also work or not at all, not even play the animation

**Comment by Smigg-y** [comment]
weird that the animation plays, will look into this
